import type { Bank, BankSummary } from '../../types/api';

export type { Bank, BankSummary };

export const LOCAL_BANKS: readonly Bank[] = [
  {
    code: 'ayandeh',
    display_name: 'بانک آینده',
    aliases: ['بانک آینده'],
    logo_url: null,
    brand_color_light: '#E67E22',
    brand_color_dark: '#B85F14',
  },
  {
    code: 'parsian',
    display_name: 'بانک پارسیان',
    aliases: ['بانک پارسیان'],
    logo_url: null,
    brand_color_light: '#8B1E3F',
    brand_color_dark: '#6E1832',
  },
  {
    code: 'pasargad',
    display_name: 'بانک پاسارگاد',
    aliases: ['بانک پاسارگاد'],
    logo_url: null,
    brand_color_light: '#F5A623',
    brand_color_dark: '#C48412',
  },
  {
    code: 'tejarat',
    display_name: 'بانک تجارت',
    aliases: ['بانک تجارت'],
    logo_url: null,
    brand_color_light: '#003DA5',
    brand_color_dark: '#002D7A',
  },
  {
    code: 'refah',
    display_name: 'بانک رفاه کارگران',
    aliases: ['بانک رفاه کارگران'],
    logo_url: null,
    brand_color_light: '#16A085',
    brand_color_dark: '#117A65',
  },
  {
    code: 'saman',
    display_name: 'بانک سامان',
    aliases: ['بانک سامان'],
    logo_url: null,
    brand_color_light: '#00A0E3',
    brand_color_dark: '#007FB5',
  },
  {
    code: 'sepah',
    display_name: 'بانک سپه',
    aliases: ['بانک سپه'],
    logo_url: null,
    brand_color_light: '#1B4F72',
    brand_color_dark: '#153D59',
  },
  {
    code: 'sina',
    display_name: 'بانک سینا',
    aliases: ['بانک سینا'],
    logo_url: null,
    brand_color_light: '#2C3E50',
    brand_color_dark: '#1A252F',
  },
  {
    code: 'shahr',
    display_name: 'بانک شهر',
    aliases: ['بانک شهر'],
    logo_url: null,
    brand_color_light: '#8E44AD',
    brand_color_dark: '#6C3483',
  },
  {
    code: 'saderat',
    display_name: 'بانک صادرات ایران',
    aliases: ['بانک صادرات ایران', 'بانک صادرات'],
    logo_url: null,
    brand_color_light: '#1A7A3A',
    brand_color_dark: '#14622E',
  },
  {
    code: 'keshavarzi',
    display_name: 'بانک کشاورزی',
    aliases: ['بانک کشاورزی'],
    logo_url: null,
    brand_color_light: '#229954',
    brand_color_dark: '#1A7439',
  },
  {
    code: 'maskan',
    display_name: 'بانک مسکن',
    aliases: ['بانک مسکن'],
    logo_url: null,
    brand_color_light: '#27AE60',
    brand_color_dark: '#1E8449',
  },
  {
    code: 'mellat',
    display_name: 'بانک ملت',
    aliases: ['بانک ملت'],
    logo_url: null,
    brand_color_light: '#E21836',
    brand_color_dark: '#C4112C',
  },
  {
    code: 'melli',
    display_name: 'بانک ملی ایران',
    aliases: ['بانک ملی ایران', 'بانک ملی'],
    logo_url: null,
    brand_color_light: '#0057A0',
    brand_color_dark: '#004080',
  },
];
